Several updates: created generic textinput and entry, mock server, api requests, headmate reducer, system map headmate list, add headmate form
Multiplied-By-One/MBOne-Frontend pull request #36
Opened 2021-06-16 01:51 UTC by allina606

generic textinput
- includes label and input field, horizontal 

generic entry
- fulfilled requirements for issue #18 

mock server, json-server folder
- created mock json-server
- db.json file contains json for headmates data

Context and Reducer, context folder
- context completed for headmates.
- context for traits in progress
- duplicate code issue when creating context and provider - more details on discord front end chat

system map headmate list 
- entire system map home page fully developed to list out headmate data pulled from mock json-server
- headmate list is a separate component imported into system map

add headmate form
- component adds headmate to database using user input form 
- imported into system map page 
- image button links nowhere 

custom container
- edited to reflect given UI from melissa better 

generic button
- added on click test / functionality 

file restructure components folder
- separate components into "generic" and page related components. so far only components for the page system map have been created 
- generic components will usually be dumb components and used throughout all pages
- page related components will usually be smart and only used for a particular page
- future enhancement that should be done: get rid of all folders in generic folder because they are unnecessary / awkward

2021-06-16 02:01 UTC, allina606 commented
![Screen Shot 2021-05-13 at 10 18 00 PM](https://user-images.githubusercontent.com/26211170/122146429-0b157700-ce25-11eb-90f2-f020ca7628e5.png)
![Screen Shot 2021-05-13 at 10 19 20 PM](https://user-images.githubusercontent.com/26211170/122146460-18cafc80-ce25-11eb-8eda-8575e758f7b8.png)
![Screen Shot 2021-05-13 at 10 19 33 PM](https://user-images.githubusercontent.com/26211170/122146476-208aa100-ce25-11eb-9997-afcaae818d64.png)

2021-10-25 16:40 UTC, tsukimi2 requested changes
Thanks for helping out with writing a significant portion of the system map feature! Just a few questions here and there in the code submitted plus some questions about the use of context provider + reducer in the headmate list and add headmate form components.  Please see comments further below for detail.  Hopefully can see you contributing further code again in the near future!  ^_^

2021-10-25 16:40 UTC, tsukimi2 commented on package.json
> +    "react-redux": "^7.2.3",
Just want to make sure.  Is redux currently in use in the application?

2021-10-25 16:40 UTC, tsukimi2 commented on package.json
> +    "redux-thunk": "^2.3.0",
Is redux currently in use in the application?

2021-10-25 16:40 UTC, tsukimi2 commented on src/api/jsonServer.js
> +})
Is this file for containing the axios.create() which is what other axios requests for sending requests to backend api are extended upon in general? Or is it specifically for the mock json-server only? If it is for sending request to backend api in general, perhaps renaming it to a more appropriate name is better? Or else when looking at the name api/jsonServer.js, I have the impression that it's for making api requests to the mock json-server only.

2021-10-25 16:40 UTC, tsukimi2 commented on src/components/generic/genericEntry/GenericEntry.js
> +    }
I think the code for systemMapEntry() should be for eyeSpaceProfileEntry(), and vice versa?

2021-10-25 16:40 UTC, tsukimi2 commented on src/components/generic/genericEntry/GenericEntry.js
> +      else if (subText==undefined && age==undefined) {
In my opinion, I think this.props.age might be too specific.  What happens if we are making use of this component variant but the info for the third line is not age but something else? Maybe changing the prop age to a more generic name is more suitable?

2021-10-25 16:40 UTC, tsukimi2 commented on src/components/generic/genericEntry/GenericEntry.stories.js
> +}
It seems like the args in SystemMap.args and the args in EyeProfile.args should be switched with each other?

2021-10-25 16:40 UTC, tsukimi2 commented on src/components/system-map/HeadmateForm.js
> +}
Same as in HeadmateList.js, are there any advantages in using context provider + reducers instead of just using simple axios calls to submit form data?

2021-10-25 16:40 UTC, tsukimi2 commented on src/components/system-map/HeadmateList.js
> +}
In this file, it seems that the HeadmateList component is using context provider (which in turn retrieves the headmate list data from HeadmateReducer) to obtain headmate list data to display the headmate list.  I’m just wondering, instead of depending on the local context provider and reducer, whether it’s simpler to just write wrapper functions to wrap the axios data request functions in some service/api-util files (or alternatively maybe use something like useSWR for that purpose??) and call those wrapper request functions instead of depending on the local context provider? Because in my understanding, using context providers is usually a good solution when the data in the context provider are application-wide data (or span a large section of the application) that you wish to maintain state.  On the other hand, if the data is used mostly locally, then we might want to consider more carefully about the potential tradeoff from using context provider such as increased code complexity and increased difficulty in writing unit/functionality testing code, like need to mock out the context provider before testing).  Or do you have some specific reasons behind why it is more advantageous to use context provider and reducers in this case?

2021-10-25 16:40 UTC, tsukimi2 commented on src/context/HeadmateContext.js
> +// export const Provider;
Looking at the code, do you intend this file to be a file to store all the reducer action functions for headmate instead of to be used as context provider (there is a code block between lines 64-67 that deals with create context, but since this code block is not being exported, it doesn’t seem like it will be able to function as a context provider).  If so, it may be less confusing if the filename and the directory it is residing in reflects that it is related to reducers rather than context.

2021-10-25 16:40 UTC, tsukimi2 commented on src/context/TraitsContext.js
> +}
From what I can see in the code, it seems this file is mainly used for displaying the list of traits in the selection box in system map edit profile form only.  Are traits required to be kept as state data in this application? If yes, then retrieving data and keeping the data in state may be a good solution; if not, then maybe straightforward wrapper functions to wrap around axios requests may be sufficient and may lead to simpler application code and testing code?

Also, is this file in use anywhere in the app? I can’t seem to find where this file is being imported.

2021-10-25 16:40 UTC, tsukimi2 commented on src/context/createContext.js
> +}
Just want to clarify what's your proposed usage of createContext.js?  I did a quick search and it doesn't seem to be used in any of the most updated code in your branch currently.  It seems to be used in src/context/HeadmateContext.js line 64 to 67

```
const { Context, Provider } = createContext(
    HeadmateReducer, 
    { addheadmate, deleteheadmate, editheadmate, getheadmates },
)
```

But since this block of code is not being exported, it does not look like this block of code can be used anywhere else in the app and thus in effect it seems to me src/context/createContext.js is not currently being used anywhere in the codebase.  So I would just like to clarify whether you are intending it to be used as something to abstract out the context provider in our app in the future? Or is it a file that is not to be used anymore and should be deleted (I see blocks of very similar context provider code in src/components/system-map/HeadmateForm.js lines 12-28 and src/components/system-map/HeadmateList.js lines 12-35 that seem to be almost like replicas of the code in src/context/createContext.js).

If the code is intended to be kept as a means to abstract out context providers in the future, then perhaps the code can be made more flexible by replacing “addFunction, deleteFunction, editFunction, getFunction” in line 6 with actions and also removing line 12 (“const actions = {addFunction, deleteFunction, editFunction, getFunction};”)? This way, createContext.js can abstract out any additional actions that any future context providers may have instead of being limited to just the actions add,delete,edit, and get.

2021-11-07 20:57 UTC, merged